#!/bin/bash 
 
clear 
 
echo "This script will give us environment information" 
echo "================================================" 
echo "" 
echo "Hello Username:azahar $username" 
echo "" 
echo "Your Home Directory is:kota $HOME" 
echo "" 
echo "Your History File Will Ignore:nothing $HISTCONTROL" 
echo "" 
echo "Your Terminal Session Type is:anything $TERM" 
echo ""
